<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    
    <link rel="stylesheet" href="assets/css/style.css" type="text/css" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alumni+Sans:ital,wght@0,100..900;1,100..900&family=Figtree:ital,wght@0,300..900;1,300..900&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=PT+Sans+Narrow:wght@400;700&family=Roboto:ital,wght@0,100..900;1,100..900&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <title><?= $layoutTitle ?></title>
</head>


<body class="layoutContainer">

    <header class="headerContainer">
        <h2>3WA Tasks</h2>
        <a href="index.php"><i class="fa-regular fa-house"></i></a>
        <a href="account.php"><i class="fa-regular fa-circle-user"></i></a>
        <a href="usertasks.php"><i class="fa-regular fa-rectangle-list"></i></a>
        <a href="edit.php"><i class="fa-regular fa-pen-to-square"></i></a>
        <a href="ranking.php"><i class="fa-solid fa-ranking-star"></i></a>
        <a href="logout.php"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
    </header>

    <main class="mainContainer">
        <?php include $template ?>
    </main>

    <footer class="footerContainer">
        <p>© 2024 - 3W Academy</p>
    </footer>
</body>
</html>