<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    
    <link rel="stylesheet" href="assets/css/style.css" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">

    
    <title>Titre</title>
</head>


<body class="layoutContainer">
    
    <header class="headerContainer">
        <h2>3WA Tasks</h2>
    </header>

    <?php include $template ?>
    
    <footer class="footerContainer">
        <p>© 2024 - 3W Academy</p>
    </footer>
</body>
</html>