<section class="accountContainer">
    <h1>Account</h1>
    
    <h2>Your tasks</h2>
    
    <article class="taskContainer">
        <h3 class="title">Task 1</h3>
        <p class="content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, voluptate.</p>
        <ul>
            <label for="">Urgent</label>
            <input type="checkbox">
            <input type="checkbox">
            <label for="">Important</label>
        </ul>
        <button class = "validate"><i class="fa-solid fa-check"></i></button>
        <button class = "modify"><i class="fa-solid fa-pen"></i></button>
        <button class = "delete"><i class="fa-regular fa-trash-can"></i></button>
    </article>



</section>