<section class="editTaskContainer"> 
    <h1>Edit Task</h1>

    <form action="update_task.php" method="post">
        
        <div>
            <label for="taskTitle">Title</label>
            <input type="text" id="taskTitle" name="title">
        </div>
        <div>
            <label for="taskContent">Content</label>
            <input type="text" name="taskContent">
        </div>

        <div>
            <label for="urgent">Urgent</label>
            <button type="checkbox">
                
            <label for="important">Important</label>
            <button type="checkbox">

            <button type="submit">Save</button>
        </div>
    </form>

</section>
