<section class="editTaskContainer"> 
    <h1>Edit Task</h1>

    <form method="post">
        
        <div>
            <label for="taskTitle">Title</label>
            <input type="text" id="taskTitle" name="title">
        </div>
        <div>
            <label for="taskContent">Content</label>
            <input type="text" name="taskContent">
        </div>

    <div class="switchBlock">

            <div class="switch-item">
            <p>Urgent</p>
            <label class="switch">
                <input type="checkbox" name="urgent" id="urgent">
                <span class="slider"></span>
            </label>
            </div>

        <div class="switch-item">
        <p>Important</p>
        <label class="switch">
            <input type="checkbox" name="important" id="important">
            <span class="slider"></span>
        </label>
        </div>

        <button type="submit">Save</button>

        </div>

    </form>

</section>