
<section class="indexContainer">
    <article>
        <h1>3WA Tasks</h1>
        <h2>The best way to optimize your time</h2>
        <p>Based on the Eisenhower method, our application give you the best order to do what you have to do.</p>
        
        <div>
            <button href="register.php">Register</button>
            <button href="login.php">Login</button>
        </div>
    </article>
    <article>
        <img src="assets/img/todo-list.png" alt="To do list">
    </article>
</section>