
<section class="indexContainer">
    <article>
        <h1>3WA Tasks</h1>
        <h2>The best way to optimize your time</h2>
        <p>Based on the Eisenhower method, our application give you the best order to do what you have to do.</p>
        
        <div>
            <button type="button" onclick="window.location.href='../register.php'">Register</button>
            <button type="button" onclick="window.location.href='../login.php'">Login</button>
        </div>
    </article>
    <article>
        <img src="../assets/img/Checklist-rafiki.svg" alt="todo list illustration">
    </article>
</section>