<section class="registerContainer">
    <h1>Register</h1>
    <p>Welcome in the world of perfect task priorization !</p>
    
    <form action="register.php" method="post" class="registerForm">
        <div>
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div>
            <label for="email">Email</label>
            <input type="email" name="email" id="email" required>
        </div>
        <div>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
        </div>
        <button type="submit">Register</button>
    </form>
</section>        