<section class="accountContainer">
    <h1>Account</h1>
    
    <h2>Your tasks</h2>
    
    <article class="taskContainer">
        <h3 class="title">Task 1</h3>
        <p class="content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, voluptate.</p>
        <div class="buttonsContainer">
            <ul>
                <div>
                    <label for="">Urgent</label>
                    <input type="checkbox">
                </div>
                <div>
                    <label for="">Important</label>
                    <input type="checkbox">
                </div>
            </ul>
            <div class="buttons">
                <button class = "validate"><i class="fa-solid fa-check"></i></button>
                <button class = "modify"><i class="fa-solid fa-pen"></i></button>
                <button class = "delete"><i class="fa-regular fa-trash-can"></i></button>
            </div>
        </div>
    </article>
    <article class="newTaskContainer">
        <h3 class="title">New task</h3>
        <form method="post">
            <div>
                <label for="title">Title</label>
                <input type="text" name="title" id="title">
            </div>
            <div>
                <label for="content">Content</label>
                <textarea name="content" id="content" cols="30" rows="10"></textarea>
            </div>
            <div class="checkboxes">
                <div>
                    <label for="urgent">Urgent</label>
                    <input type="checkbox" name="urgent" id="urgent">
                </div>
                <div>
                    <label for="important">Important</label>
                    <input type="checkbox" name="important" id="important">
                </div>
            </div>

            <button type="submit">Add task</button>
        </form>
    </article>
</section>